name: Flake Build

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  flake-build:
    name: Build Nix flake
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Build default package
        run: nix build .#default --print-build-logs
